version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: scooter_db
    environment:
      POSTGRES_USER: scooter_user
      POSTGRES_PASSWORD: scooter_password
      POSTGRES_DB: scooter_rental
    ports:
      - "5434:5432"
    restart: unless-stopped
  redis:
    image: redis:7.2-alpine
    container_name: scooter-redis
    ports:
      - "6379:6379"
    restart: unless-stopped