spring.datasource.url=jdbc:postgresql://localhost:5434/scooter_rental
spring.datasource.username=scooter_user
spring.datasource.password=scooter_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true