ALTER TABLE scooters ADD COLUMN version INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN version INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN balance DECIMAL(12, 2) NOT NULL DEFAULT 0.00;
